version: "3.7"
services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-client
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
    volumes:
      - ./:/app

# spark-worker-2:
#   image: bde2020/spark-worker:2.4.5-hadoop2.7
#   container_name: spark-worker-2
#   depends_on:
#     - spark-master
#   ports:
#     - "8081:8081"
#   environment:
#     - "SPARK_MASTER=spark://spark-master:7077"
#     - "constraint:node==<yourworkernode>" 
