# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  postgres-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-client
    depends_on:
      - database
    environment:
      - "POSTGRES_HOST=database"

volumes:
  database-data: # named volumes can be managed easier using docker-compose
